//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicoSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicoSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        ///00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        ///00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        ///00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        /* internal static string font {
            get {
                return ResourceManager.GetString("font", resourceCulture);
            }
        } */
        
        /// <summary>
        ///   Looks up a localized string similar to function all(t)
        ///  if t ~= nil then
        ///    local nt = {}
        ///    local ni = 1
        ///    for _,v in pairs(t) do
        ///      nt[ni] = v
        ///      ni = ni + 1
        ///    end
        ///    for k,v in pairs(nt) do
        ///    end
        ///
        ///    local i = 0
        ///    return function() i = i + 1; return nt[i] end
        ///  end
        ///  return function() end
        ///end
        ///
        ///function add(t, v)
        ///  if t ~= nil then
        ///    t[#t+1] = v
        ///    return v
        ///  end
        ///end
        ///
        ///function foreach(c, f)
        ///  if c ~= nil then
        ///    for key, value in ipairs(c) do
        ///      f(value)
        ///    end
        ///  end
        ///end
        ///
        ///
        ///function ma [rest of string was truncated]&quot;;.
        /// </summary>
        /* internal static string LuaApi {
            get {
                return ResourceManager.GetString("LuaApi", resourceCulture);
            }
        } */
    }
}
